CREATE DATABASE IF NOT EXISTS tracking_db;
USE tracking_db;

CREATE TABLE IF NOT EXISTS pixel_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    event VARCHAR(255) NOT NULL,
    data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
